<?php

$labels = array();

// mail

$labels['folder_contact'] = 'Contact folder';

$labels['folder_create'] = 'Créer un dossier';
$labels['folder_delete'] = 'Supprimer un dossier';
$labels['folder_rename'] = 'Renommer un dossier';
$labels['folder_locate'] = 'Localiser un dossier';

$labels['folder_purge'] = 'Purger le dossier';

$labels['folder_read_this'] = 'Marquer le dossier comme lu';
$labels['folder_read_tree'] = 'Folder tree read';

$labels['show_all'] = 'Afficher tout';
$labels['show_active'] = 'Afficher actifs';
$labels['show_favorite'] = 'Afficher Favoris';

$labels['folder_select'] = 'Sélectionner le dossier';
$labels['folder_unselect'] = 'Déselectionner le dossier';

$labels['reset_selected'] = 'Réinitialiser la sélection';
$labels['reset_transient'] = 'Reset transient';

$labels['status_title'] = 'Folder view...';

$labels['folder_expand_all'] = 'Développer tout';
$labels['folder_collapse_all'] = 'Réduire tout';

$labels['folder'] = 'Dossier';

$labels['reset'] = 'Réinitialiser';
$labels['apply'] = 'Appliquer';
$labels['cancel'] = 'Annuler';
$labels['select'] = 'Selectionner';
$labels['search'] = 'Rechercher';

$labels['source'] = 'Source';
$labels['target'] = 'Cible';

$labels['create'] = 'Créer';
$labels['delete'] = 'Supprimer';
$labels['rename'] = 'Renommer';
$labels['locate'] = 'Localiser';

$labels['parent'] = 'Parent';
$labels['header'] = 'En-tête';
$labels['format'] = 'Format';
$labels['type'] = 'Type';
$labels['full_name'] = 'Nom complet';
$labels['mail_addr'] = 'Adresse Mail';

$labels['message_copy'] = 'Copier vers...';
$labels['message_move'] = 'Déplacer vers...';

// settings

$labels['plugin_folder_menu'] = 'Plugin: Folder Menu';

$labels['activate_plugin'] = 'Activate plugin';

$labels['enable_logging'] = 'Enable plugin logging';
$labels['enable_refresh'] = 'Enable folder tree refresh';
$labels['enable_folder_list_context_menu'] = 'Enable mailbox list context menu';
$labels['enable_folder_list_control_menu'] = 'Enable mailbox list control menu';
$labels['enable_message_list_context_menu'] = 'Enable message list context menu';

$labels['feature_choice'] = 'Enable plugin features';

$labels['filter_active'] = 'Filters in category "active"';
$labels['filter_favorite'] = 'Filters in category "favorite"';

$labels['predefined_list'] = 'Folders in "predefined" filter';
$labels['contact_folder_format_list'] = 'Contact mailbox format templates';

$labels['transient_expire_mins'] = 'Transient folder expiration time (mins)';

?>
