#!/bin/bash
#export VERBOSE=1 #STDOUT normal, STDERR en rouge
#export VERBOSE=2 #STDOUT pas affiché. STDERR en rouge
#export VERBOSE=3 #STDOUT et STDERR pas affiché (mode silencieux)
export VERBOSE=2

export DOMAIN=
export AES_KEY=auto
export WEBMAIL_DES_KEY=auto
export UUID=auto

export LAST_UPGRADE=

export MODULE_APACHE=
export MODULE_API=
export MODULE_BACKUP=
export MODULE_CLOUD=
export MODULE_CRYPT=
export MODULE_DECRYPT=
export MODULE_DISKPART=
export MODULE_LETSENCRYPT=
export MODULE_MAILSERVER=
export MODULE_MARIADB=
export MODULE_MARIADB_REMOTE_ACCESS=
export MODULE_OPTIMUS=
export MODULE_PHP=
export MODULE_SECURE_UPDATE=
export MODULE_SECURE_ENABLEFW=
export MODULE_SECURE_FAIL2BAN=
export MODULE_SECURE_CHANGEROOTPASS=
export MODULE_SECURE_CHANGEDEBIANPASS=
export MODULE_SECURE_SSH_REPLACEDEFAULTPORT=
export MODULE_SECURE_SSH_DISABLEROOTACCESS=
export MODULE_SECURE_SSH_2FA=
export MODULE_UPGRADE=
export MODULE_WEBMAIL=
export MODULE_WWW=

export DISKPART_DISK_TO_PART=
export DISKPART_USE_FREESPACE=
export DISKPART_RESIZE_PARTITION=
export PART_TO_ENCRYPT=

export SECURE_GOOGLEAUTH_KEY=
export SECURE_ROOT_PASSWORD=auto
export SECURE_DEBIAN_PASSWORD=auto

export MARIADB_ADMIN_USER=prime@$DOMAIN
export MARIADB_ADMIN_PASSWORD=auto
export MARIADB_REMOTE_ROOT_PASSWORD=auto
export MARIADB_DB_VERSION=

export CLOUD_MARIADB_USER=cloud
export CLOUD_MARIADB_PASSWORD=auto
export CLOUD_DB_VERSION=

export MAILSERVER_MARIADB_USER=mailboxes
export MAILSERVER_MARIADB_PASSWORD=auto
export MAILSERVER_POSTMASTER_MAILBOX_USER=prime@$DOMAIN
export MAILSERVER_POSTMASTER_MAILBOX_PASSWORD=auto
export MAILSERVER_DB_VERSION=
